Le_Domain='back.zoronaliverooms.com'
Le_Alt='no'
Le_Webroot='/data/www/back.zoronaliverooms.com'
Le_PreHook=''
Le_PostHook=''
Le_RenewHook=''
Le_API='https://acme-v02.api.letsencrypt.org/directory'
Le_Keylength='ec-256'
Le_OrderFinalize='https://acme-v02.api.letsencrypt.org/acme/finalize/1027079687/190435374587'
Le_LinkOrder='https://acme-v02.api.letsencrypt.org/acme/order/1027079687/190435374587'
Le_LinkCert='https://acme-v02.api.letsencrypt.org/acme/cert/03856ef088f6ec3ef9db03f24469039123cf'
Le_CertCreateTime='1687527344'
Le_CertCreateTimeStr='2023-06-23T13:35:44Z'
Le_NextRenewTimeStr='2023-08-21T13:35:44Z'
Le_NextRenewTime='1692624944'
